### ISSUE TITLE
Where can I get the compiled project?

### ISSUE THREAD

**Issue by brend8c** [caesay/defsound#4]
I need a compiled project with a ready exe file to run

**Comment by caesay** [comment]
You can compile this library yourself, or there are other pre-made applications based on it's code available elsewhere. I do not endorse these but just a few examples: 
- https://github.com/Belphemur/SoundSwitch 
- https://github.com/xenolightning/AudioSwitcher_v1

**Comment by brend8c** [comment]
I haven't worked with C++, can you edit the readme.md file and write how to compile this file correctly, step by step?

**Comment by caesay** [comment]
This is not originally my library and I don't intend to make any updates/fixes to this project. I imported (saved) it from CodePlex. You can see the original repository page here. https://web.archive.org/web/20170901000000*/https://defsound.codeplex.com

Instructions for building: Open `DefSound.sln` in Visual Studio, then press F6.

I have uploaded a compiled exe here: https://github.com/caesay/defsound/releases
